### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by jagrg** [mparusinski/wikiquotes-downloader#1]
On Debian Wheezy, I get this error:

```
# python DownloadQuotes.py --author "Friedrich Nietzsche"
Traceback (most recent call last):
  File "DownloadQuotes.py", line 96, in <module>
    main()
  File "DownloadQuotes.py", line 68, in main
    json_contents.append(wiki_retriever.download_quote(a_philosophers_name))
  File "/home/jag/wikiquotes-downloader/WikiquotesRetriever.py", line 50, in download_quote
    self.curler.setopt(self.curler.WRITEDATA, buffer_string)
TypeError: invalid arguments to setopt
```

I'm also getting an error on OS X 10.10.3:

```
$ python DownloadQuotes.py --author "Friedrich Nietzsche"
Traceback (most recent call last):
  File "DownloadQuotes.py", line 96, in <module>
    main()
  File "DownloadQuotes.py", line 73, in main
    irinstances = map(ir_from_json, json_contents)
  File "/Users/jag/wikiquotes-downloader/InternalRepresentation.py", line 232, in ir_from_json
    return InternalRepresentation(wikitext_from_json(json_content))
  File "/Users/jag/wikiquotes-downloader/InternalRepresentation.py", line 229, in wikitext_from_json
    raise InvalidWikitext("Not a valid JSON string")
InternalRepresentation.InvalidWikitext: 'Not a valid JSON string'
```

**Comment by mparusinski** [comment]
I haven't worked on this for a while. Let me have a look.

**Comment by mparusinski** [comment]
Wikiquotes switched to HTTPS, and the code was not up to date.

Fixed in latest commits

**Comment by jagrg** [comment]
Great, thank you!
